// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB3Dj-iExYIeC_dJIcIYL9MQXY4Ais6A8',
    appId: '1:568842008318:web:707e2c8135b63e9830d7af',
    messagingSenderId: '568842008318',
    projectId: 'humanresources-a285c',
    authDomain: 'humanresources-a285c.firebaseapp.com',
    storageBucket: 'humanresources-a285c.appspot.com',
    measurementId: 'G-935X3MW3J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpSCaJRsR0BrAYnbMZ3m1I6VSjvhp4Kac',
    appId: '1:568842008318:android:a36e0dc040675c0130d7af',
    messagingSenderId: '568842008318',
    projectId: 'humanresources-a285c',
    storageBucket: 'humanresources-a285c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBENCAot_BGPUsmeGDD8RfMBEeaeJiXPTI',
    appId: '1:568842008318:ios:610c08061f81d5a230d7af',
    messagingSenderId: '568842008318',
    projectId: 'humanresources-a285c',
    storageBucket: 'humanresources-a285c.appspot.com',
    iosClientId: '568842008318-lh3cn11mc2jqem385iifbikfh6vshbft.apps.googleusercontent.com',
    iosBundleId: 'com.example.newHumanResource',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBENCAot_BGPUsmeGDD8RfMBEeaeJiXPTI',
    appId: '1:568842008318:ios:610c08061f81d5a230d7af',
    messagingSenderId: '568842008318',
    projectId: 'humanresources-a285c',
    storageBucket: 'humanresources-a285c.appspot.com',
    iosClientId: '568842008318-lh3cn11mc2jqem385iifbikfh6vshbft.apps.googleusercontent.com',
    iosBundleId: 'com.example.newHumanResource',
  );
}
